<!DOCTYPE HTML>
<html lang="kr" class="sidebar-visible no-js rust">
    <head>
        <!-- Book generated using mdBook -->
        <meta charset="UTF-8">
        <title>Error Handling - Study: Rust Programming Language 2nd edition</title>


        <!-- Custom HTML head -->
        
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="theme-color" content="#ffffff" />

        <link rel="icon" href="favicon.svg">
        <link rel="shortcut icon" href="favicon.png">
        <link rel="stylesheet" href="css/variables.css">
        <link rel="stylesheet" href="css/general.css">
        <link rel="stylesheet" href="css/chrome.css">
        <link rel="stylesheet" href="css/print.css" media="print">

        <!-- Fonts -->
        <link rel="stylesheet" href="FontAwesome/css/font-awesome.css">
        <link rel="stylesheet" href="fonts/fonts.css">

        <!-- Highlight.js Stylesheets -->
        <link rel="stylesheet" href="highlight.css">
        <link rel="stylesheet" href="tomorrow-night.css">
        <link rel="stylesheet" href="ayu-highlight.css">

        <!-- Custom theme stylesheets -->

        <!-- MathJax -->
        <script async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    </head>
    <body>
        <!-- Provide site root to javascript -->
        <script>
            var path_to_root = "";
            var default_theme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "navy" : "rust";
        </script>

        <!-- Work around some values being stored in localStorage wrapped in quotes -->
        <script>
            try {
                var theme = localStorage.getItem('mdbook-theme');
                var sidebar = localStorage.getItem('mdbook-sidebar');

                if (theme.startsWith('"') && theme.endsWith('"')) {
                    localStorage.setItem('mdbook-theme', theme.slice(1, theme.length - 1));
                }

                if (sidebar.startsWith('"') && sidebar.endsWith('"')) {
                    localStorage.setItem('mdbook-sidebar', sidebar.slice(1, sidebar.length - 1));
                }
            } catch (e) { }
        </script>

        <!-- Set the theme before any content is loaded, prevents flash -->
        <script>
            var theme;
            try { theme = localStorage.getItem('mdbook-theme'); } catch(e) { }
            if (theme === null || theme === undefined) { theme = default_theme; }
            var html = document.querySelector('html');
            html.classList.remove('no-js')
            html.classList.remove('rust')
            html.classList.add(theme);
            html.classList.add('js');
        </script>

        <!-- Hide / unhide sidebar before it is displayed -->
        <script>
            var html = document.querySelector('html');
            var sidebar = 'hidden';
            if (document.body.clientWidth >= 1080) {
                try { sidebar = localStorage.getItem('mdbook-sidebar'); } catch(e) { }
                sidebar = sidebar || 'visible';
            }
            html.classList.remove('sidebar-visible');
            html.classList.add("sidebar-" + sidebar);
        </script>

        <nav id="sidebar" class="sidebar" aria-label="Table of contents">
            <div class="sidebar-scrollbox">
                <ol class="chapter"><li class="chapter-item expanded affix "><a href="introduction.html">Introduction</a></li><li class="chapter-item expanded "><a href="chapter_01.html"><strong aria-hidden="true">1.</strong> Getting Started</a></li><li class="chapter-item expanded "><a href="chapter_02.html"><strong aria-hidden="true">2.</strong> Programming a Guessing Game</a></li><li class="chapter-item expanded "><a href="chapter_03.html"><strong aria-hidden="true">3.</strong> Common Programming Concepts</a></li><li class="chapter-item expanded "><a href="chapter_04.html"><strong aria-hidden="true">4.</strong> Understanding Ownership</a></li><li class="chapter-item expanded "><a href="chapter_05.html"><strong aria-hidden="true">5.</strong> Using Structs to Structure Related Data</a></li><li class="chapter-item expanded "><a href="chapter_06.html"><strong aria-hidden="true">6.</strong> Enums and Pattern Matching</a></li><li class="chapter-item expanded "><a href="chapter_07.html"><strong aria-hidden="true">7.</strong> Managing Growing Projects with Packages, Crates, and Modules</a></li><li class="chapter-item expanded "><a href="chapter_08.html"><strong aria-hidden="true">8.</strong> Common Collections</a></li><li class="chapter-item expanded "><a href="chapter_09.html" class="active"><strong aria-hidden="true">9.</strong> Error Handling</a></li><li class="chapter-item expanded "><a href="chapter_10.html"><strong aria-hidden="true">10.</strong> Generic Types, Traits, and Lifetimes</a></li><li class="chapter-item expanded "><a href="chapter_11.html"><strong aria-hidden="true">11.</strong> Writing Automated Tests</a></li><li class="chapter-item expanded "><a href="chapter_12.html"><strong aria-hidden="true">12.</strong> An I/O Project: Building a Command Line Program</a></li><li class="chapter-item expanded "><a href="chapter_13.html"><strong aria-hidden="true">13.</strong> Functional Language Features: Iterators and Closures</a></li><li class="chapter-item expanded "><a href="chapter_14.html"><strong aria-hidden="true">14.</strong> More About Cargo and Crates.io</a></li><li class="chapter-item expanded "><a href="chapter_15.html"><strong aria-hidden="true">15.</strong> Smart Pointers</a></li><li class="chapter-item expanded "><a href="chapter_16.html"><strong aria-hidden="true">16.</strong> Fearless Concurrency</a></li><li class="chapter-item expanded "><a href="chapter_17.html"><strong aria-hidden="true">17.</strong> Object-Oriented Programming Features</a></li><li class="chapter-item expanded "><a href="chapter_18.html"><strong aria-hidden="true">18.</strong> Patterns and Matching</a></li><li class="chapter-item expanded "><a href="chapter_19.html"><strong aria-hidden="true">19.</strong> Advanced Features</a></li><li class="chapter-item expanded "><a href="chapter_20.html"><strong aria-hidden="true">20.</strong> Final Project: Building a Multithreaded Web Server</a></li></ol>
            </div>
            <div id="sidebar-resize-handle" class="sidebar-resize-handle"></div>
        </nav>

        <div id="page-wrapper" class="page-wrapper">

            <div class="page">
                                <div id="menu-bar-hover-placeholder"></div>
                <div id="menu-bar" class="menu-bar sticky bordered">
                    <div class="left-buttons">
                        <button id="sidebar-toggle" class="icon-button" type="button" title="Toggle Table of Contents" aria-label="Toggle Table of Contents" aria-controls="sidebar">
                            <i class="fa fa-bars"></i>
                        </button>
                        <button id="theme-toggle" class="icon-button" type="button" title="Change theme" aria-label="Change theme" aria-haspopup="true" aria-expanded="false" aria-controls="theme-list">
                            <i class="fa fa-paint-brush"></i>
                        </button>
                        <ul id="theme-list" class="theme-popup" aria-label="Themes" role="menu">
                            <li role="none"><button role="menuitem" class="theme" id="light">Light</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="rust">Rust</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="coal">Coal</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="navy">Navy</button></li>
                            <li role="none"><button role="menuitem" class="theme" id="ayu">Ayu</button></li>
                        </ul>
                        <button id="search-toggle" class="icon-button" type="button" title="Search. (Shortkey: s)" aria-label="Toggle Searchbar" aria-expanded="false" aria-keyshortcuts="S" aria-controls="searchbar">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>

                    <h1 class="menu-title">Study: Rust Programming Language 2nd edition</h1>

                    <div class="right-buttons">
                        <a href="print.html" title="Print this book" aria-label="Print this book">
                            <i id="print-button" class="fa fa-print"></i>
                        </a>
                        <a href="https://github.com/jerok-kim/rust_lang_book" title="Git repository" aria-label="Git repository">
                            <i id="git-repository-button" class="fa fa-github"></i>
                        </a>

                    </div>
                </div>

                <div id="search-wrapper" class="hidden">
                    <form id="searchbar-outer" class="searchbar-outer">
                        <input type="search" id="searchbar" name="searchbar" placeholder="Search this book ..." aria-controls="searchresults-outer" aria-describedby="searchresults-header">
                    </form>
                    <div id="searchresults-outer" class="searchresults-outer hidden">
                        <div id="searchresults-header" class="searchresults-header"></div>
                        <ul id="searchresults">
                        </ul>
                    </div>
                </div>

                <!-- Apply ARIA attributes after the sidebar and the sidebar toggle button are added to the DOM -->
                <script>
                    document.getElementById('sidebar-toggle').setAttribute('aria-expanded', sidebar === 'visible');
                    document.getElementById('sidebar').setAttribute('aria-hidden', sidebar !== 'visible');
                    Array.from(document.querySelectorAll('#sidebar a')).forEach(function(link) {
                        link.setAttribute('tabIndex', sidebar === 'visible' ? 0 : -1);
                    });
                </script>

                <div id="content" class="content">
                    <main>
                        <h1 id="error-handling"><a class="header" href="#error-handling">Error Handling</a></h1>
<p>Errors are a fact of life in software, so Rust has a number of features for handling situations in which something goes
wrong. In many cases, Rust requires you acknowledge the possibility of an error and take some action before your code
will compile. This requirement makes your program more robust by ensuring that you'll discover errors and handle them
appropriately before deploying your code to production!</p>
<p>Rust groups errors into two major categories: recoverable and unrecoverable errors. For a recoverable error, such as a
file not found error, we most likely just want to report the problem to the user and retry the operation. Unrecoverable
errors are always symptoms of bugs, such as trying to access a location beyond the end of an array, and so we want to
immediately stop the program.</p>
<p>Most languages don't distinguish between these two kinds of errors and handle both in the same way, using mechanisms
such as exceptions. Rust doesn't have exceptions. Instead, it has the type <code>Result&lt;T, E&gt;</code> for recoverable errors and
the <code>panic!</code> macro that stops execution when the program encounters an unrecoverable error. This chapter covers
calling <code>panic!</code> first and then talks about returning <code>Result&lt;T, E&gt;</code> values. Additionally, we'll explore considerations
when deciding whether to try to recover from an error or to stop execution.</p>
<h2 id="unrecoverable-errors-with-panic"><a class="header" href="#unrecoverable-errors-with-panic">Unrecoverable Errors with panic!</a></h2>
<p>Sometimes bad things happen in your code, and there's nothing you can do about it. In these cases, Rust has the <code>panic!</code>
macro. There are two ways to cause a panic in practice: by taking an action that causes our code to panic(such as
accessing an array past the end) or by explicitly calling the <code>panic!</code> macro. In both cases, we cause a panic in our
program. By default, these panics will print a failure message, unwind, clean up the stack, and quit. Via an environment
variable, you can also have Rust display the call stack when a panic occurs to make it easier to track down the source
of the panic.</p>
<blockquote>
<h4 id="unwinding-the-stack-or-aborting-in-response-to-a-panic"><a class="header" href="#unwinding-the-stack-or-aborting-in-response-to-a-panic">Unwinding the stack or aborting in response to a panic</a></h4>
<p>By default, when a panic occurs the program starts unwinding, which means Rust walks back up the stack and cleans up
the data from each function it encounters. However, walking back and cleaning up is a lot of work. Rust, therefore,
allows you to choose the alternative of immediately aborting, which ends the program without cleaning up.</p>
<p>Memory that the program was using will then need to be cleaned up by the operating system. If in your project you need
to make the resultant binary as small as possible, you can switch from unwinding to aborting upon a panic by
adding <code>panic = 'abort'</code> to the appropriate <code>[profile]</code> sections in your <code>Cargo.toml</code> file. For example, if you want
to
abort on panic in release mode, add this:</p>
<pre><code class="language-toml">[profile.release]
panic = 'abort'
</code></pre>
</blockquote>
<p>Let's try calling <code>panic!</code> in a simple program:</p>
<pre><pre class="playground"><code class="language-rust  editable edition2021">fn main() {
    panic!(&quot;crash and burn&quot;);
}</code></pre></pre>
<p>When you run the program, you'll see something like this:</p>
<pre><code class="language-text">thread 'main' panicked at 'crash and burn', src\main.rs:2:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
</code></pre>
<p>The call to <code>panic!</code> causes the error message contained in the last two lines. The first line shows our panic message
and the place in our source code where the panic occurred: <code>src/main.rs:2:5</code> indicates that it's the second line, fifth
character of our <code>src/main.rs</code> file.</p>
<p>In this case, the line indicated is part of our code, and if we go to that line, we see the <code>panic!</code> macro call. In
other cases, the <code>panic!</code> call might be in code that our code calls, and the filename and line number reported by the
error message will be someone else's code where the <code>panic!</code> macro is called, not the line of our code that eventually
led to the <code>panic!</code> call.</p>
<p>We can use the backtrace of the functions the <code>panic!</code> call came from to figure out the part of our code that is causing
the problem. To understand how to use a <code>panic!</code> backtrace, let's look at another example and see what it's like when
a <code>panic!</code> call comes from a library because of a bug in our code instead of from our code calling the macro directly.
Listing 9-1 has some code that attempts to access an index in a vector beyond the range of valid indexes.</p>
<pre><pre class="playground"><code class="language-rust  editable edition2021">fn main() {
    let v = vec![1, 2, 3];
    
    v[99];
}</code></pre></pre>
<ul>
<li>Listing 9-1: Attempting to access an element beyond the end of a vector, which will cause a call to <code>panic!</code></li>
</ul>
<p>Here, we're attempting to access the 100th element of our vector (which is at index 99 because indexing starts at zero),
but the vector has only three elements. In this situation, Rust will panic. Using <code>[]</code> is supposed to return an element,
but if you pass an invalid index, there's no element that Rust could return here that would be correct.</p>
<p>In C, attempting to read beyond the end of a data structure is undefined behavior. You might get whatever is at the
location in memory that would correspond to that element in the data structure, even though the memory doesn't belong to
that structure. This is called a buffer overread and can lead to security vulnerabilities if an attacker is able to
manipulate the index in such a way as to read data they shouldn't be allowed to that is stored after the data structure.</p>
<p>To protect your program from this sort of vulnerability, if you try to read an element at an index that doesn't exist,
Rust will stop execution and refuse to continue. Let's try it and see:</p>
<pre><code class="language-text">thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 99', src\main.rs:4:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</code></pre>
<p>This error points at line 4 of our <code>main.rs</code> where we attempt to access <code>index</code>. The <code>note:</code> line tells us that we can
set the <code>RUST_BACKTRACE</code> environment variable to get a backtrace of exactly what happened to cause the error. A
backtrace is a list of all the functions that have been called to get to this point. Backtraces in Rust work as they do
in other languages: the key to reading the backtrace is to start from the top and read until you see files you wrote.
That's the spot where the problem originated. The lines above that spot are code that your code has called; the lines
below are code that called your code. These before-and-after lines might include core Rust code, standard library code,
or crates that you're using. Let's try getting a backtrace by setting the <code>RUST_BACKTRACE</code> environment variable to any
value except <code>0</code>. Listing 9-2 shows output similar to what you'll see.</p>
<pre><code class="language-text">thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 99', src\main.rs:4:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\core\src\panicking.rs:64
   2: core::panicking::panic_bounds_check
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\core\src\panicking.rs:147
   3: core::slice::index::impl$2::index&lt;i32&gt;
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\slice\index.rs:260
   4: core::slice::index::impl$0::index
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\slice\index.rs:18
   5: alloc::vec::impl$15::index&lt;i32,usize,alloc::alloc::Global&gt;
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\alloc\src\vec\mod.rs:2727
   6: ch09::main
             at .\src\main.rs:4
   7: core::ops::function::FnOnce::call_once&lt;void (*)(),tuple$&lt;&gt; &gt;
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405\library\core\src\ops\function.rs:507
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</code></pre>
<ul>
<li>Listing 9-2: The backtrace generated by a call to <code>panic!</code> displayed when the environment variable <code>RUST_BACKTRACE</code> is
set</li>
</ul>
<p>That's a lot of output! The exact output you see might be different depending on your operating system and Rust version.
In order to get backtraces with this information, debug symbols must be enabled. Debug symbols are enabled by default
when using <code>cargo build</code> or <code>cargo run</code> without the <code>--release</code> flag, as we have here.</p>
<p>In the output in Listing 9-2, line 6 of the backtrace points to the line in our project that's causing the problem: line
4 of <code>src/main.rs</code>. If we don't want our program to panic, we should start our investigation at the location pointed too
by the first line mentioning a file we wrote. In Listing 9-1, where we deliberately wrote code that would panic, the way
to fix the panic is to not request an element beyond the range of the vector indexes. When your code panics in the
future, you'll need to figure out what action the code is taking with what values to cause the panic and what the code
should do instead.</p>
<p>We'll come back to <code>panic!</code> and when we should and should not use <code>panic!</code> to handle error conditions in &quot;To panic! or
Not to panic!&quot;. Next, we'll look at how to recover from an error using <code>Result</code>.</p>
<h2 id="recoverable-errors-with-result"><a class="header" href="#recoverable-errors-with-result">Recoverable Errors with Result</a></h2>
<p>Most errors aren't serious enough to require the program to stop entirely. Sometimes when a function fails it's for a
reason that you can easily interpret and respond to. For example, if you try to open a file and that operation fails
because the file doesn't exist, you might want to create the file instead of terminating the process.</p>
<p>Recall from &quot;Handling Potential Failure with Result&quot; that the <code>Result</code> enum is defined as having two variants, <code>Ok</code>
and <code>Err</code>, as follows:</p>
<pre><code class="language-rust  noplayground">enum Result&lt;T, E&gt; {
    Ok(T),
    Err(E),
}</code></pre>
<p>The <code>T</code> and <code>E</code> are generic type parameters: we'll discuss generics in more detail in Chapter 10. What you need to know
right now is that <code>T</code> represents the type of the value that will be returned in a success case within the <code>Ok</code> variant,
and <code>E</code> represents the type of the error that will be returned in a failure case within the <code>Err</code> variant.
Because <code>Result</code> has these generic type parameters, we can use the <code>Result</code> type and the functions defined on it in many
different situations where the success value and error value we want to return may differ.</p>
<p>Let's call a function that returns a <code>Result</code> value because the function could fail. In Listing 9-3 we try to open a
file.</p>
<pre><code class="language-rust  noplayground">use std::fs::File;

fn main() {
    let greeting_file_result = File::open(&quot;hello.txt&quot;);
}</code></pre>
<ul>
<li>Listing 9-3: Opening a file</li>
</ul>
<p>The return type of <code>File::open</code> is a <code>Result&lt;T, E&gt;</code>. The generic parameter <code>T</code> has been filled in by the implementation
of <code>File::open</code> with the type of the success value, <code>std::fs::File</code>, which is a file handle. The type of <code>E</code> used in the
error value is <code>std::io::Error</code>. This return type means the call to <code>File::open</code> might succeed and return a file handle
that we can read from or write to. The function call also might fail: for example, the file might not exist, or we might
not have permission to access the file. The <code>File::open</code> function needs to have a way to tell us whether it succeeded of
failed and at the same time give us either the file handle or error information. This information is exactly what
the <code>Result</code> enum conveys.</p>
<p>In the case where <code>File::open</code> succeeds, the value in the variable <code>greeting_file_result</code> will be an instance of <code>Ok</code>
that contains a file handle. In the case where it fails, the value in <code>greeting_file_result</code> will be an instance
of <code>Err</code> that contains more information about the kind of error that occurred.</p>
<p>We need to add to the code in Listing 9-3 to take different actions depending on the value <code>File::open</code> returns. Listing
9-4 shows one way to handle the <code>Result</code> using a basic tool, the <code>match</code> expression that we discussed in Chapter 6.</p>
<pre><code class="language-rust  noplayground">use std::fs::File;

fn main() {
    let greeting_file_result = File::open(&quot;hello.txt&quot;);

    let greeting_file = match greeting_file_result {
        Ok(file) =&gt; file,
        Err(error) =&gt; {
            panic!(&quot;Problem opening the file: {:?}&quot;, error);
        }
    };
}</code></pre>
<ul>
<li>Listing 9-4: Using a <code>match</code> expression to handle the <code>Result</code> variants that might be returned</li>
</ul>
<p>Note that, like the <code>Option</code> enum, the <code>Result</code> enum and its variants have been brought into scope by the prelude, so we
don't need to specify <code>Result::</code> before the <code>Ok</code> and <code>Err</code> variants in the <code>match</code> arms.</p>
<p>When the result is <code>Ok</code>, this code will return the inner <code>file</code> value out of the <code>Ok</code> variant, and we then assign that
file handle value to the variable <code>greeting_file</code>. After the <code>match</code>, we can use the file handle for reading or writing.</p>
<p>The other arm of the <code>match</code> handles the case where we get an <code>Err</code> value from <code>File::open</code>. In this example, we've
chosen to call the <code>panic!</code> macro. If there's no file named hello.txt in our current directory and we run this code,
we'll see the following output from the <code>panic!</code> macro:</p>
<pre><code class="language-text">thread 'main' panicked at 'Problem opening the file: Os { code: 2, kind: NotFound, message: &quot;The system cannot find the file specified.&quot; }', src\main.rs:9:13
</code></pre>
<p>As usual, this output tells us exactly what has gone wrong.</p>
<h3 id="matching-on-different-errors"><a class="header" href="#matching-on-different-errors">Matching on Different Errors</a></h3>
<p>The code in Listing 9-4 will <code>panic!</code> no matter why <code>File::open</code> failed. However, we want to take different actions for
different failure reasons. If <code>File::open</code> failed because the file doesn't exist, we want to create the file and return
the handle to the new file. If <code>File::open</code> failed for any other reason - for example, because we didn't have permission
to open the file - we still want the code to <code>panic!</code> in the same way it did in Listing 9-4. For this, we add an
inner <code>match</code> expression, shown in Listing 9-5.</p>
<pre><code class="language-rust  noplayground">use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file_result = File::open(&quot;hello.txt&quot;);

    let greeting_file = match greeting_file_result {
        Ok(file) =&gt; file,
        Err(error) =&gt; match error.kind() {
            ErrorKind::NotFound =&gt; {
                match File::create(&quot;hello.txt&quot;) {
                    Ok(fc) =&gt; fc,
                    Err(e) =&gt; panic!(
                        &quot;Problem creating the file: {:?}&quot;,
                        e
                    ),
                }
            }
            other_error =&gt; {
                panic!(
                    &quot;Problem opening the file: {:?}&quot;,
                    other_error
                );
            }
        },
    };
}</code></pre>
<ul>
<li>Listing 9-5: Handling different kinds of errors in different ways</li>
</ul>
<p>The type of the value that <code>File::open</code> returns inside the <code>Err</code> variants is <code>io::Error</code>, which is a struct provided by
the standard library. This struct has a method <code>kind</code> that we can call to get an <code>io::ErrorKind</code> value. The
enum <code>io::ErrorKind</code> is provided by the standard library and has variants representing the different kinds of errors
that might result from an <code>io</code> operation. The variant we want to use is <code>ErrorKind::NotFound</code>, which indicates the file
we're trying to open doesn't exist yet. So we match on <code>greeting_file_result</code>, but we also have an inner match
on <code>error.kind()</code>.</p>
<p>The condition we want to check in the inner match is whether the value returned by <code>error.kind()</code> is the <code>NotFound</code>
variant of the <code>ErrorKind</code> enum. If it is, we try to create the file with <code>File::create</code>. However,
because <code>File::create</code> could also fail, we need a second arm in the inner <code>match</code> expression. When the file can't be
created, a different error message is printed. The second arm of the outer <code>match</code> stays the same, so the program panics
on any error besides the missing file error.</p>
<h4 id="alternatives-to-using-match-with-resultt-e"><a class="header" href="#alternatives-to-using-match-with-resultt-e">Alternatives to Using match with Result&lt;T, E&gt;</a></h4>
<p>That's a lot of <code>match</code>! The <code>match</code> expression is very useful but also very much a primitive. In Chapter 13, you'll
learn about closures, which are used with many of the methods defined on <code>Result&lt;T, E&gt;</code>. These methods can be more
concise than using <code>match</code> when handling <code>Result&lt;T, E&gt;</code> values in your code.</p>
<p>For example, here's another way to write the same logic as shown in Listing 9-5, this time using closures and
the <code>unwrap_or_else</code> method:</p>
<pre><code class="language-rust  noplayground">use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file_result = File::open(&quot;hello.txt&quot;).unwrap_or_else(|error| {
        if error.kind() == ErrorKind::NotFound {
            File::create(&quot;hello.txt&quot;).unwrap_or_else(|error| {
                panic!(&quot;Problem creating the file: {:?}&quot;, error);
            })
        } else {
            panic!(&quot;Problem opening the file: {:?}&quot;, error);
        }
    });
}</code></pre>
<p>Although this code has the same behavior as Listing 9-5, it doesn't contain any <code>match</code> expressions and is cleaner to
read. Come back to this example after you've read Chapter 13, and look up the <code>unwrap_or_else</code> method in the standard
library documentation. Many more of these methods can clean up huge nested <code>match</code> expressions when you're dealing with
errors.</p>
<h4 id="shortcuts-for-panic-on-error-unwrap-and-expect"><a class="header" href="#shortcuts-for-panic-on-error-unwrap-and-expect">Shortcuts for Panic on Error: unwrap and expect</a></h4>
<p>Using <code>match</code> works well enough, but it can be a bit verbose and doesn't always communicate intent well.
The <code>Result&lt;T, E&gt;</code> type has many helper methods defined on it to do various, more specific tasks. The <code>unwrap</code> method is
a shorcut method implemented just like the <code>match</code> expression we wrote in Listing 9-4. If the <code>Result</code> value is the <code>Ok</code>
variant, <code>unwrap</code> will return the value inside the <code>Ok</code>. If the <code>Result</code> is the <code>Err</code> variant, <code>unwrap</code> will call
the <code>panic!</code> macro for us. Here is an example of <code>unwrap</code> in action:</p>
<pre><pre class="playground"><code class="language-rust  editable edition2021">use std::fs::File;

fn main() {
    let greeting_file = File::open(&quot;hello.txt&quot;).unwrap();
}</code></pre></pre>
<p>If we run this code without a hello.txt file, we'll see an error message from the <code>panic!</code> call that the <code>unwrap</code> method
makes:</p>
<pre><code class="language-text">thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: &quot;The system cannot find the file specified.&quot; }', src\main.rs:4:49
</code></pre>
<p>Similarly, the <code>expect</code> method lets us also choose the <code>panic!</code> error message. Using <code>expect</code> instead of <code>unwrap</code> and
providing good error messages can convey your intent and make traking down the source of a panic easier. The syntax
of <code>expect</code> looks like this:</p>
<pre><pre class="playground"><code class="language-rust  editable edition2021">use std::fs::File;

fn main() {
    let greeting_file = File::open(&quot;hello.txt&quot;)
        .expect(&quot;hello.txt should be included in this project&quot;);
}</code></pre></pre>
<p>We use <code>expect</code> in the same way as <code>unwrap</code>: to return the file handle or call the <code>panic!</code> macro. The error message
used by <code>expect</code> in its call to <code>panic!</code> will be the parameter that we pass to <code>expect</code>, rather than the
default <code>panic!</code> message that <code>unwrap</code> uses. Here's what it looks like:</p>
<pre><code class="language-text">thread 'main' panicked at 'hello.txt should be included in this project: Os { code: 2, kind: NotFound, message: &quot;The system cannot find the file specified.&quot; }', src\main.rs:5:10
</code></pre>
<p>In production-quality code, most Rustaceans choose <code>expect</code> rather than <code>unwrap</code> and give more context about why the
operation is expected to always succeed. That way, if your assumptions are ever proven wrong, you have more information
to use in debugging.</p>
<h3 id="propagating-errors"><a class="header" href="#propagating-errors">Propagating Errors</a></h3>
<p>When a function's implementation calls something that might fail, instead of handling the error within the function
itself, you can return the error to the calling code so that it can decide what to do. This is known as propagating the
error and gives more control to the calling code, where there might be more information or logic that dictates how the
error should be handled than what you have available in the context of your code.</p>
<p>For example, Listing 9-6 shows a function that reads a username from a file. If the file doesn't exist or can't be read,
this function will return those errors to the code that called the function.</p>
<pre><code class="language-rust  noplayground">use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {     // 1
    let username_file_result = File::open(&quot;hello.txt&quot;);         // 2

    let mut username_file = match username_file_result {        // 3
        Ok(file) =&gt; file,           // 4
        Err(e) =&gt; return Err(e),    // 5
    };

    let mut username = String::new();       // 6

    match username_file.read_to_string(&amp;mut username) {         // 7
        Ok(_) =&gt; Ok(username),      // 8
        Err(e) =&gt; Err(e),           // 9
    }
}</code></pre>
<ul>
<li>Listing 9-6: A function that returns errors to the calling code using <code>match</code></li>
</ul>
<p>This function can be written in a much shorter way, but we're going to start by doing a lot of it manually in order to
explore error handling; at the end, we'll show the shorter way. Let's look at the return type of the function
first: <code>Result&lt;String, io::Error&gt;</code> (1). This means the function is returning a value of the type <code>Result&lt;T, E&gt;</code>, where
the generic parameter <code>T</code> has been filled in with the concrete type <code>String</code> and the generic type <code>E</code> has been filled in
with the concrete type <code>io::Error</code>.</p>
<p>If this function succeeds without any problems, the code that calls this function will receive an <code>Ok</code> value that holds
a <code>String</code> - the <code>username</code> that this function read from the file (8). If this function encounters any problems, the
calling code will receive an <code>Err</code> value that holds an instance of <code>io::Error</code> that contains more information about what
the problems were. We chose <code>io::Error</code> as the return type of this function because that happens to be the type of the
error value returned from both of the operations we're calling in this function's body that might fail: the <code>File::open</code>
function (2) and the <code>read_to_string</code> method (7).</p>
<p>The body of the function starts by calling the <code>File::open</code> function (2). Then we handle the <code>Result</code> value with
a <code>match</code> similar to the <code>match</code> in Listing 9-4. If <code>File::open</code> succeeds, the file handle in the pattern
variable <code>file</code> (4) becomes the value in the mutable variable <code>username_file</code> (3) and the function continues. In
the <code>Err</code> case, instead of calling <code>panic!</code>, we use the <code>return</code> keyword to return ealy out of the function entirely and
pass the error value from <code>File::open</code>, now in the pattern variable, <code>e</code>, back to the calling code as this function's
error value (5).</p>
<p>So, if we have a file handle in <code>username_file</code>, the function then creates a new <code>String</code> in variable <code>username</code> (6) and
calls the <code>read_to_string</code> method on the file handle in <code>username_file</code> to read the contents of thef ile
into <code>username</code> (7). The <code>read_to_string</code> method also returns a <code>Result</code> because is might fail, even though <code>File::open</code>
succeeds, then our function has succeeded, and we return the username from the file that's now in <code>username</code> wrapped in
an <code>Ok</code>. If <code>read_to_string</code> fails, we return the error value in the same way that we returned the error value in
the <code>match</code> that handled the return value of <code>File::open</code>. However, we don't need to explicitly say <code>return</code>, because
this is the last expression in the function (9).</p>
<p>The code that calls this code will then handle getting either an <code>Ok</code> value that contains a username or an <code>Err</code> value
that contains an <code>io::Error</code>. It's up to the calling code to decide what to do with those values. If the calling code
gets an <code>Err</code> value, it could call <code>panic!</code> and crash the program, use a default username, or look up the username from
somewhere other than a file, for example. We don't have enough information on what the calling code is actually trying
to do, so we propagate all thes success or error information upward for it to handle appropriately.</p>
<p>This pattern of propagating errors is so common in Rust that Rust provides the question mark operator <code>?</code> to make this
easier.</p>
<h4 id="a-shortcut-for-propagating-errors-the--operator"><a class="header" href="#a-shortcut-for-propagating-errors-the--operator">A Shortcut for Propagating Errors: The ? Operator</a></h4>
<p>Listing 9-7 shows an implementation of <code>read_username_from_file</code> that has the same functionality as in Listing 9-6, but
this implementation uses the <code>?</code> operator.</p>
<pre><code class="language-rust  noplayground">use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {
    let mut username_file = File::open(&quot;hello.txt&quot;)?;
    let mut username = String::new();
    username_file.read_to_string(&amp;mut username)?;
    Ok(username)
}</code></pre>
<ul>
<li>Listing 9-7: A function that returns errors to the calling code using the <code>?</code> operator</li>
</ul>
<p>The <code>?</code> placed after a <code>Result</code> value is defined to work in almost the same way as the <code>match</code> expressions we defined to
handle the <code>Result</code> values in Listing 9-6. If the value of the <code>Result</code> is an <code>Ok</code>, the value the value inside the <code>Ok</code>
will get returned from this expression, and the program will continue. If the value is an <code>Err</code>, the <code>Err</code> will be
returned from the whole function as if we had used the <code>return</code> keyword so the error value gets propagated to the
calling code.</p>
<p>There is a difference between what the <code>match</code> expression from Listing 9-6 does and what the <code>?</code> operator does: error
values that have the <code>?</code> operator called on them go through the <code>from</code> function, defined in the <code>From</code> trait in the
standard library, which is used to convert values from one type into another. When the <code>?</code> operator calls the <code>from</code>
function, the error type received is converted into the error type defined in the return type of the current function.
This is useful when a function returns one error type to represent all the ways a function might fail, even if parts
might fail for many different reasons.</p>
<p>For example, we could change the <code>read_username_from_file</code> function in Listing 9-7 to return a custom error type
named <code>OurError</code> that we define. If we also define <code>impl From&lt;io::Error&gt; for OurError</code> to construct an instance
of <code>OurError</code> from an <code>io::Error</code>, then the <code>?</code> operator calls in the body of <code>read_username_from_file</code> will call <code>from</code>
and convert the error types without needing to add any more code to the function.</p>
<p>In the context of Listing 9-7, the <code>?</code> at the end of the <code>File::open</code> call will return the value inside an <code>Ok</code> to the
variable <code>username_file</code>. If an error occurs, the <code>?</code> operator will return early out of the whole function and give
any <code>Err</code> value to the calling code. The same thing applies to the <code>?</code> at the end of the <code>read_to_string</code> call.</p>
<p>The <code>?</code> operator eliminates a lot of boilerplate and makes this function's implementation simpler. We could even shorten
this code further by chaining method calls immediately after the <code>?</code>, as shown in Listing 9-8.</p>
<pre><code class="language-rust  noplayground">use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {
    let mut username = String::new();

    File::open(&quot;hello.txt&quot;)?.read_to_string(&amp;mut username)?;

    Ok(username)
}</code></pre>
<ul>
<li>Listing 9-8: Chaining method calls after the <code>?</code> operator</li>
</ul>
<p>We've moved the creation of the new <code>String</code> in <code>username</code> to the beginning of the function; that part hasn't changed.
Instead of creating a variable <code>username_file</code>, we've chained the call to <code>read_to_string</code> directly onto the result
of <code>File::open(&quot;hello.txt&quot;)?</code>. We still have a <code>?</code> at the end of the <code>read_to_string</code> call and we still return an <code>Ok</code>
value containing <code>username</code> when both <code>File::open</code> and <code>read_to_string</code> succeed rather than returning errors. The
functionality is again the same as in Listing 9-6 and Listing 9-7; this is just a different, more ergonoomic way to
write it.</p>
<p>Listing 9-9 shows a way to make this even shorter using <code>fs::read_to_string</code>.</p>
<pre><code class="language-rust  noplayground">use std::fs;
use std::io;

fn read_username_from_file() -&gt; Result&lt;String, io::Error&gt; {
    fs::read_to_string(&quot;hello.txt&quot;)
}</code></pre>
<ul>
<li>Listing 9-9: Using <code>fs::read_to_string</code> instead of opening and then reading the file</li>
</ul>
<p>Reading a file into a string is a fairly common operation, so the standard library provides the
convenient <code>fs::read_to_string</code> function that opens the file, creates a new <code>String</code>, reads the contents of the file,
puts the contents into that <code>String</code>, and returns it. Of course, using <code>fs::read_to_string</code> doesn't give us the
opportunity to explain all the error handling, so we did it the longer way first.</p>
<h4 id="where-the--operator-can-be-used"><a class="header" href="#where-the--operator-can-be-used">Where the ? Operator Can Be Used</a></h4>
<p>The <code>?</code> operator can only be used in functions whose return type is compatible with the value the <code>?</code> is used on. This
is because the <code>?</code> operator is defined to perform an early return of a value out of the function, in the same manner as
the <code>match</code> expression we defined in Listing 9-6. In Listing 9-6, the <code>match</code> was using a <code>Result</code> value, and the early
return arm returned an <code>Err(e)</code> value. The return type of the function has to be a <code>Result</code> so that it's compatible with
this <code>return</code>.</p>
<p>In Listing 9-10, let's look at the error we'll get if we use the <code>?</code> operator in a <code>main</code> function with a return type
that is incompatible with the type of the value we use <code>?</code> on.</p>
<pre><pre class="playground"><code class="language-rust  no playground edition2021">use std::fs::File;

fn main() {
    let greeting_file = File::open(&quot;hello.txt&quot;)?;
}</code></pre></pre>
<ul>
<li>Listing 9-10: Attempting to use the <code>?</code> in the <code>main</code> function that returns <code>()</code> won't compile.</li>
</ul>
<p>This code opens a file, which might fail. The <code>?</code> operator follows the <code>Result</code> value returned by <code>File::open</code>, but
this <code>main</code> function has the return type of <code>()</code>, not <code>Result</code>. When we compile this code, we get the following error
message:</p>
<pre><code class="language-text">error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `FromResidual`)
  --&gt; src\main.rs:13:48
   |
12 | fn main() {
   | --------- this function should return `Result` or `Option` to accept `?`
13 |     let greeting_file = File::open(&quot;hello.txt&quot;)?;
   |                                                ^ cannot use the `?` operator in a function that returns `()`
   |
   = help: the trait `FromResidual&lt;Result&lt;Infallible, std::io::Error&gt;&gt;` is not implemented for `()`
</code></pre>
<p>This error points out that we're only allowed to use the <code>?</code> operator in a function that returns <code>Result</code>, <code>Option</code>, or
another type that implements <code>FromResidual</code>.</p>
<p>To fix the error, you have two choices. One choice is to change the return type of your function to be compatible with
the value you're using the <code>?</code> operator on as long as you have no restrictions preventing that. The other choice is to
use a <code>match</code> or one of the <code>Result&lt;T, E&gt;</code> methods to handle the <code>Result&lt;T, E&gt;</code> in whatever way is appropriate.</p>
<p>The error message also mentioned that <code>?</code> can be used with <code>Option&lt;T&gt;</code> values as well. As with using <code>?</code> on <code>Result</code>,
you can only use <code>?</code> on <code>Option</code> in a function that returns an <code>Option</code>. The behavior of the <code>?</code> operator when called on
an <code>Option&lt;T&gt;</code> is similar to its behavior when called on a <code>Result&lt;T, E&gt;</code>: if the value is <code>None</code>, the <code>None</code> will be
returned early from the function at that point. If the value is <code>Some</code>, the value inside the <code>Some</code> is the resultant
value of the expression, and the function continues. Listing 9-11 has an example of a function that finds the last
character of the first line in the given text</p>
<pre><code class="language-rust  noplayground">fn last_char_of_first_line(text: &amp;str) -&gt; Option&lt;char&gt; {
    text.lines().next()?.chars().last()
}</code></pre>
<ul>
<li>Listing 9-11: Using the <code>?</code> operator on an <code>Option&lt;T&gt;</code> value</li>
</ul>
<p>This function returns <code>Option&lt;char&gt;</code> because it's possible that there is a character there, but it's also possible that
there isn't. This code takes the <code>text</code> string slice argument and calls the <code>lines</code> method on it, which returns an
iterator over the lines in the string. Because this function wants to examine the first line, it calls <code>next</code> on the
iterator to get the first value from the iterator. If <code>text</code> is the empty string, this call to <code>next</code> will
return <code>None</code>, in which case we use <code>?</code> to stop and return <code>None</code> from <code>last_char_of_first_line</code>. If <code>text</code> is not the
empty string, <code>next</code> will return a <code>Some</code> value containing a string slice of the first line in <code>text</code>.</p>
<p>The <code>?</code> extracts the string slice, and we call call <code>chars</code> on that string slice to get an iterator of its characters.
We're interested in the last character in this first line, so we call <code>last</code> to return the last item in the iterator.
This is an <code>Option</code> because it's possible that the first line is the empty string; for example, if <code>text</code> starts with a
black line but has characters on other lines, as in <code>&quot;\nhi&quot;</code>. However, if there is a last character on the first line,
it will be returned in the <code>Some</code> variant. The <code>?</code> operator in the middle gives us a concise way to express this logic,
allowing us to implement the function in one line. If we couldn't use the <code>?</code> operator on <code>Option</code>, we'd have to
implement this logic using more method calls or a <code>match</code> expression.</p>
<p>Note that you can use the <code>?</code> operator on a <code>Result</code> in a function that returns <code>Result</code>, and you can use the <code>?</code>
operator on an <code>Option</code>. in a function that returns <code>Option</code>, but you can't mix and match. The <code>?</code> operator won't
automatically convert a <code>Result</code> to an <code>Option</code> or vice versa; in those cases, you can use methods like the <code>ok</code> method
on <code>Result</code> or the <code>ok_or</code> method on <code>Option</code> to do the conversion explicitly.</p>
<p>So far, all the <code>main</code> functions we've used return <code>()</code>. The <code>main</code> function is special because it's the entry point and
exit point of an executable program, and there are restrictions on what its return type can be for the program to behave
as expected.</p>
<p>Luckily, <code>main</code> can also return a <code>Result&lt;(), E&gt;</code>. Listing 9-12 has the code from Listing 9-10, but we've changed the
return type of <code>main</code> to be <code>Result&lt;(), Box&lt;dyn Error&gt;&gt;</code> and added a return value <code>Ok(())</code> to the end. This code will
now compile.</p>
<pre><pre class="playground"><code class="language-rust edition2021">use std::error::Error;
use std::fs::File;

fn main() -&gt; Result&lt;(), Box&lt;dyn Error&gt;&gt; {
    let greeting_file = File::open(&quot;hello.txt&quot;)?;

    Ok(())
}</code></pre></pre>
<ul>
<li>Listing 9-12: Changing <code>main</code> to return <code>Result&lt;(), E&gt;</code> allows the use of the <code>?</code> operator on <code>Result</code> values.</li>
</ul>
<p>The <code>Box&lt;dyn Error&gt;</code> type is a trait object, which we'll talk about in &quot;Using Trait Objects That Allow for Values of
Different Types&quot;. For now, you can read <code>Box&lt;dyn Error&gt;</code> to mean &quot;any kind of error&quot;. Using <code>?</code> on a <code>Result</code> value in
a <code>main</code> function with the error type <code>Box&lt;dyn Error&gt;</code> is allowed because it allows any <code>Err</code> value to be returned
early. Even though the body of this <code>main</code> function will only ever return errors to type <code>std::io::Error</code>, by
specifying <code>Box&lt;dyn Error&gt;</code>, this signature will continue to be correct even if more code that returns other errors is
added to the body of <code>main</code>.</p>
<p>When a <code>main</code> function returns a <code>Result&lt;(), E&gt;</code>, the executable will exit with a value of <code>0</code> if <code>main</code>
returns <code>Ok(())</code> and will exit with a nonzero value if <code>main</code> returns an <code>Err</code> value. Executables written in C return
integers when they exit: programs that exit successfully return the integer <code>0</code>, and programs that error return some
integer other than <code>0</code>. Rust also returns integers from executables to be compatible with this convention.</p>
<p>The <code>main</code> function may return any types that implement the <code>std::process::Termination</code> trait, which contains a
function <code>report</code> that returns an <code>ExitCode</code>. Consult the standard library documentation for more information on
implementing the <code>Termination</code> trait for your own types.</p>
<p>Now that we've discussed the details of calling <code>panic!</code> or returning <code>Result</code>, let's return to the topic of how to
decide which is appropriate to use in which cases.</p>
<h2 id="to-panic-or-not-to-panic"><a class="header" href="#to-panic-or-not-to-panic">To panic! or Not to panic!</a></h2>
<p>So how do you decide when you should call <code>panic!</code> and when you should return <code>Result</code>? When code panics, there's no way
to recover. You could call <code>panic!</code> for any error situation, whether there's a possible way to recover or not, but then
you're making the decision that a situation is unrecoverable on behalf of the calling code. When you choose to return
a <code>Result</code> value, you give the calling code options. The calling code could choose to attempt to recover in a way that's
appropriate for its situation, or it could decide that an <code>Err</code> value in this case is unrecoverable, so it can
call <code>panic!</code> and turn your recoverable error into an unrecoverable one. Therefore, returning <code>Result</code> is a good default
choice when you're defining a function that might fail.</p>
<p>In situations such as examples, prototype code, and tests, it's more appropriate to write code that panics instead of
returning a <code>Result</code>. Let's explore why, then discuss situations in which the compiler can't tell that failure is
impossible, but you as a human can. The chapter will conclude with some general guidelines on how to decide whether to
panic in library code.</p>
<h3 id="examples-prototype-code-and-tests"><a class="header" href="#examples-prototype-code-and-tests">Examples, Prototype Code, and Tests</a></h3>
<p>When you're writing an example to illustrate some concept, also including robust error-handling code can make the
example less clear. In examples, it's understood that a call to a method like <code>unwrap</code> that could panic is meant as a
place holder for the way you'd want your application to handle errors, which can differ based on what the rest of your
code is doing.</p>
<p>Similarly, the <code>unwrap</code> and <code>expect</code> methods are very handy when prototyping, before you're ready to decide how to
handle errors. They leave clear markers in your code for when you're ready to make your program more robust.</p>
<p>If a method call fails in a test, you'd want the whole test to fail, even if that method isn't the functionality under
test. Because <code>panic!</code> is how a test is marked as a failure, calling <code>unwrap</code> or <code>expect</code> is exactly what should happen.</p>
<h3 id="cases-in-which-you-have-more-information-than-the-compiler"><a class="header" href="#cases-in-which-you-have-more-information-than-the-compiler">Cases in Which You Have More Information Than the Compiler</a></h3>
<p>It would also be appropriate to call <code>unwrap</code> or <code>expect</code> when you have some other logic that ensures the <code>Result</code> will
have an <code>Ok</code> value, but the logic isn't something the compiler understands. You'll still have a <code>Result</code> value that you
need to handle: whatever operation you're calling still has the possibility of failing in general, even though it's
logically impossible in your particular situation. If you can ensure by manually inspecting the code that you'll never
have an <code>Err</code> variant, it's perfectly acceptable to call <code>unwrap</code>, and even better to document the reason you think
you'll never have an <code>Err</code> variant in the <code>expect</code> text. Here's an example:</p>
<pre><code class="language-rust  noplayground">use std::net::IpAddr;

let home: IpAddr = &quot;127.0.0.1&quot;
    .parse()
    .expect(&quot;Hardcoded IP address should be valid&quot;);</code></pre>
<p>We're creating an <code>IpAddr</code> instance by parsing a hardcoded string. We can see that <code>127.0.0.1</code> is a valid IP address, so
it's acceptable to use <code>expect</code> here. However, having a hardcoded valid string doesn't change the return type of
the <code>parse</code> method: we still get a <code>Result</code> value, and the compiler will still make us handle the <code>Result</code> as if
the <code>Err</code> variant is a possibility because the compiler isn't smart enough to see that this string is always a valid IP
address. If the IP address string came from a user rather than being hardcoded into the program and therefore did have a
possibility of failure, we'd definitely want to handle the <code>Result</code> in a more robust way instead. Mentioning the
assumption that this IP address is hardcoded will prompt us to change <code>expect</code> to better error-handling code if, in the
future, we need to get the IP address from some other source instead.</p>
<h3 id="guidelines-for-error-handling"><a class="header" href="#guidelines-for-error-handling">Guidelines for Error Handling</a></h3>
<p>It's advisable to have your code panic when it's possible that your code could end up in a bad state. In this context, a
bad state is when some assumption, guarantee, contract, or invariant has been broken, such as when invalid values,
contradictory values, or missing values are passed to your code - plus one or more of the following:</p>
<ul>
<li>The bad state is something that is unexpected, as opposed to something that will likely happen occasionally, like a
user entering data in the wrong format.</li>
<li>Your code after this point needs to rely on not being in this bad state, rather than checking for the problem at every
step.</li>
<li>There's not a good way to encode this information in the types you use. We'll work through an example of what we mean
in &quot;Encoding States and Behavior as Types&quot;.</li>
</ul>
<p>If someone calls your code and passes in values that don't make sense, it's best to return an error if you can so the
user of the library can decide what they want to do in that case. However, in cases where continuing could be insecure
or harmful, the best choice might be to call <code>panic!</code> and alert the person using your library to the bug in their code
so they can fix it during development. Similarly, <code>panic!</code> is often appropriate if you're calling external code that is
out of your control and it returns an invalid state that you have no way of fixing.</p>
<p>However, when failure is expected, it's more appropriate to return an <code>Result</code> than to make a <code>panic!</code> call. Examples
include a parser being given malformed data or an HTTP request returning a status that indicates you have hit a rate
limit. In these cases, returning a <code>Result</code> indicates that failure is an expected possibility that the calling code must
decide how to handle.</p>
<p>When your code performs an operation that could put a user at risk if it's called using invalid values your code should
verify the values are valid first and panic if the values aren't valid. This is mostly for safety reasons: attempting to
operate on invalid data can expose your code to vulnerabilities. This is the main reason the standard library will
call <code>panic!</code> if you attempt an out-of-bounds memory access: trying to access memory that doesn't belong to the current
data structure is a common security problem. Functions often have contracts: their behavior is only guaranteed if the
inputs meet particular requirements. Panicking when the contract is violated makes sense because a contract violation
always indicates a caller-side bug, and it's not a kind or error you want the calling code to have to explicitly handle.
In fact, there's no reasonable way for calling code to recover; the calling programmers need to fix the code. Contracts
for a function, especially when a violation will cause a panic, should be explained in the API documentation for the
function.</p>
<p>However, having lots of error checks in all of your functions would be verbose and annoying. Fortunately, you can use
Rust's type system (and thus the type checking done by the compiler) to do many of the checks for you. If your function
has a particular type as a parameter, you can proceed with your code's logic knowing that the compiler has already
ensured you have a valid value. For example, if you have a type rather than an <code>Option</code>, your program expects to have
something rather than nothing. Your code then doesn't have to handle two cases for the <code>Some</code> and <code>None</code> variants: it
will only have one case for definitely having a value. Code trying to pass nothing to your function won't even compile,
so your function doesn't have to check for that case at runtime. Another example is using an unsigned integer type such
as <code>u32</code>, which ensures the parameter is never negative.</p>
<h3 id="creating-custom-types-for-validation"><a class="header" href="#creating-custom-types-for-validation">Creating Custom Types for Validation</a></h3>
<p>Let's take the idea of using Rust's type system to ensure we have a valid value one step further and look at creating a
custom type for validation. Recall the guessing game in Chapter 2 in which our code asked the user to guess a number
between 1 and 100. We never validated that the user's guess was between those numbers before checking it against our
secret number; we only validated that the guess was positive. In this case, the consequences were not very dire: our
output of &quot;Too high&quot; or &quot;Too low&quot; would still be correct. But it would be a useful enhancement to guide the user toward
valid guesses and have different behavior when the user guesses a number that's out of range versus when the user types,
for example, letters instead.</p>
<p>One way to do this would be to parse the guess as an <code>i32</code> instead of only a <code>u32</code> to allow potentially negative
numbers, and then add a check for the number being in range, like so:</p>
<pre><code class="language-rust  noplayground">loop {
    // snip

    let guess: i32 = match guess.trim().parse() {
        Ok(num) =&gt; num,
        Err(_) =&gt; continue,
    };

    if guess &lt; 1 || guess &gt; 100 {
        println!(&quot;The secret number will be between 1 and 100.&quot;);
        continue;
    }

    match guess.cmp(&amp;secret_number) {
        // snip

}</code></pre>
<p>The <code>if</code> expression checks whether our value is out of range, tells the user about the problem, and calls <code>continue</code> to
start the next iteration of the loop and ask for another guess. After the <code>if</code> expression, we can proceed with the
comparisons between <code>guess</code> and the secret number knowing that <code>guess</code> is between 1 and 100.</p>
<p>However, this is not an ideal solution: if it were absolutely critical that the program only operated on values between
1 and 100, and it had many functions with this requirement, having a check like this in every function would be
tedious (and might impact performance).</p>
<p>Instead, we can make a new type and put the validations in a function to create an instance of the type rather than
repeating the validations every where. That way, it's safe for functions to use the new type in their signatures and
confidently use the values they receive. Listing 9-13 shows one way to define a <code>Guess</code> type that will only create an
instance of <code>Guess</code> if the <code>new</code> function receives a value between 1 and 100.</p>
<pre><code class="language-rust  noplayground">pub struct Guess {      // 1
    value: i32,
}

impl Guess {
    pub fn new(value: i32) -&gt; Guess {       // 2
        if value &lt; 1 || value &gt; 100 {       // 3
            panic!(     // 4
                &quot;Guess value must be between 1 and 100, got {}.&quot;,
                value
            );
        }
        
        Guess { value }     // 5
    }
    
    pub fn value(&amp;self) -&gt; i32 {        // 6
        self.value
    }
}</code></pre>
<ul>
<li>Listing 9-13: A <code>Guess</code> type that will only continue with values between 1 and 100</li>
</ul>
<p>First we define a struct named <code>Guess</code> that has a field named <code>value</code> that holds an <code>i32</code> (1). This is where the number
will be stored.</p>
<p>Then we implement an associated function named <code>new</code> on <code>Guess</code> that creates instances of <code>Guess</code> values (2). The <code>new</code>
function is defined to have one parameter named <code>value</code> of type <code>i32</code> and to return a <code>Guess</code>. The code in the body of
the <code>new</code> function tests <code>value</code> to make sure it's between 1 and 100 (3). If <code>value</code> doesn't pass this test, we make
a <code>panic!</code> call (4), which will alert the programmer who is writing the calling code that they have a bug they need to
fix, because creating a <code>Guess</code> with a <code>value</code> outside this range would violate the contract that <code>Guess::new</code> is
relying on. The conditions in which <code>Guess::new</code> might panic should be discussed in its public-facing API documentation;
we'll cover documentation conventions indicating the possibility of a <code>panic!</code> in the API documentation conventions
indicating the possibility of a <code>panic!</code> in the API documentation that you create in Chapter 14. If <code>value</code> does pass
the test, we create a new <code>Guess</code> with its <code>value</code> field set to the <code>value</code> parameter and return the <code>Guess</code> (5).</p>
<p>Next, we implement a method named <code>value</code> that borrows <code>self</code>, doesn't have any other parameters, and returns an <code>i32</code> (
6). This kind of method is sometimes called a getter because its purpose is to get some data from its fields and return
it. This public method is necessary because the <code>value</code> field of the <code>Guess</code> struct is private. It's important that
the <code>value</code> field be private so code using the <code>Guess</code> struct is not allowed to set <code>value</code> directly: code outside the
module must use the <code>Guess::new</code> function to create an instance of <code>Guess</code>, thereby ensuring there's no way for
a <code>Guess</code> to have a <code>value</code> that hasn't been checked by the conditions in the <code>Guess::new</code> function.</p>
<p>A function that has a parameter or returns only numbers between 1 and 100 could then declare in its signature that it
takes or returns a <code>Guess</code> rather than an <code>i32</code> and wouldn't need to do any additional checks in its body.</p>
<h2 id="summary"><a class="header" href="#summary">Summary</a></h2>
<p>Rust's error-handling features are designed to help you write more robust code. The <code>panic!</code> macro signals that your
program is in a state it can't handle and lets you tell the process to stop instead of trying to proceed with invalid or
incorrect values. The <code>Result</code> enum uses Rust's type system to indicate that operations might fail in a way that your
code could recover from. You can use <code>Result</code> to tell code that calls your code that it needs to handle potential
success or failure as well. Using <code>panic!</code> and <code>Result</code> in the appropriate situations will make your code more reliable
in the face of inevitable problems.</p>
<p>Now that you've seen useful ways that the standard library uses generics with the <code>Option</code> and <code>Result</code> enums, we'll
talk about how generics work and how you can use them in your code.</p>

                    </main>

                    <nav class="nav-wrapper" aria-label="Page navigation">
                        <!-- Mobile navigation buttons -->
                            <a rel="prev" href="chapter_08.html" class="mobile-nav-chapters previous" title="Previous chapter" aria-label="Previous chapter" aria-keyshortcuts="Left">
                                <i class="fa fa-angle-left"></i>
                            </a>

                            <a rel="next" href="chapter_10.html" class="mobile-nav-chapters next" title="Next chapter" aria-label="Next chapter" aria-keyshortcuts="Right">
                                <i class="fa fa-angle-right"></i>
                            </a>

                        <div style="clear: both"></div>
                    </nav>
                </div>
            </div>

            <nav class="nav-wide-wrapper" aria-label="Page navigation">
                    <a rel="prev" href="chapter_08.html" class="nav-chapters previous" title="Previous chapter" aria-label="Previous chapter" aria-keyshortcuts="Left">
                        <i class="fa fa-angle-left"></i>
                    </a>

                    <a rel="next" href="chapter_10.html" class="nav-chapters next" title="Next chapter" aria-label="Next chapter" aria-keyshortcuts="Right">
                        <i class="fa fa-angle-right"></i>
                    </a>
            </nav>

        </div>



        <script>
            window.playground_line_numbers = true;
        </script>

        <script>
            window.playground_copyable = true;
        </script>

        <script src="ace.js"></script>
        <script src="editor.js"></script>
        <script src="mode-rust.js"></script>
        <script src="theme-dawn.js"></script>
        <script src="theme-tomorrow_night.js"></script>

        <script src="elasticlunr.min.js"></script>
        <script src="mark.min.js"></script>
        <script src="searcher.js"></script>

        <script src="clipboard.min.js"></script>
        <script src="highlight.js"></script>
        <script src="book.js"></script>

        <!-- Custom JS scripts -->


    </body>
</html>
